feat: updates

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -43,21 +43,12 @@ outputs:
 runs:
   using: composite
   steps:
-    - name: Check token input
-      if: inputs.build-only != 'true' && inputs.github-token == ''
-      shell: bash
-      run: |
-        echo "::error::github-token input is required to publish a release. Provide a token with repo + write access."
-        exit 1
-
-    - name: Set normalized TOKEN env var
-      shell: bash
-      run: |
-        if [ -n "${{ inputs.github-token }}" ]; then
-          echo "TOKEN=${{ inputs.github-token }}" >> $GITHUB_ENV
-        else
-          echo "TOKEN=${{ github.token }}" >> $GITHUB_ENV
-        fi
+    # - name: Check token input
+    #   if: inputs.build-only != 'true' && inputs.github-token == ''
+    #   shell: bash
+    #   run: |
+    #     echo "::error::github-token input is required to publish a release. Provide a token with repo + write access."
+    #     exit 1
 
     - name: Checkout action repository
       uses: actions/checkout@v6
@@ -120,7 +111,7 @@ runs:
       shell: bash
       run: npx semantic-release --dry-run
       env:
-        GITHUB_TOKEN: ${{ env.TOKEN }}
+        GITHUB_TOKEN: ${{ inputs.github-token || github.token }}
 
     - name: Release
       if: inputs.build-only != 'true' && inputs.manual-tag != 'true'
@@ -128,7 +119,7 @@ runs:
       shell: bash
       run: npx semantic-release
       env:
-        GITHUB_TOKEN: ${{ env.TOKEN }}
+        GITHUB_TOKEN: ${{ inputs.github-token || github.token }}
 
     - name: Normalize outputs
       if: inputs.build-only != 'true'
