feat: update token logic

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -42,12 +42,17 @@ outputs:
 runs:
   using: composite
   steps:
-    - name: Check/set GITHUB_TOKEN environment variable
+    - name: Check token input
+      if: inputs.build-only != 'true' && inputs.github-token == ''
       shell: bash
       run: |
-        if [ -n "${{ inputs.github-token }}" ]; then
-          echo "GITHUB_TOKEN=${{ inputs.github-token }}" >> $GITHUB_ENV
-        fi
+        echo "::error::github-token input is required to publish a release. Provide a token with repo + write access."
+        exit 1
+
+    - name: Normalize GITHUB_TOKEN
+      if: inputs.github-token != ''
+      shell: bash
+      run: echo "GITHUB_TOKEN=${{ inputs.github-token }}" >> $GITHUB_ENV
 
     - name: Checkout action repository
       uses: actions/checkout@v6
@@ -85,13 +90,6 @@ runs:
       if: inputs.typecheck == 'true'
       shell: bash
       run: npm run typecheck
-
-    # - name: Check token
-    #   if: inputs.build-only != 'true' && inputs.github-token == ''
-    #   shell: bash
-    #   run: |
-    #     echo "::error::github-token input is required to publish a release. Provide a token with repo + write access."
-    #     exit 1
 
     - name: Check 'semantic-release-export-data' plugin
       if: inputs.build-only != 'true'
